site_name: LHM-RIBASIM documentatie
site_url: https://d2hydro.github.io/lhm-ribasim
theme:
  name: "material"
  language: nl
  logo: icons/logo/globe_only.png
  favicon: icons/logo/favicon.png
  highlightjs: true
  palette: 
    primary: blue

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/d2hydro/lhm-ribasim/
nav:
    - Home: index.md
    - Bouw LHM topologie: notebooks/bouw_lhm_topology.ipynb