name: ribasim

channels:
  - conda-forge
    
dependencies:
  - black
  - build
  - geopandas
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - mypy
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
  - mkdocs-jupyter
  - pandas
  - pandera
  - pip
  - pip:
    - xmipy
    - quartodoc
  - pyarrow
  - pydantic
  - pyogrio
  - pytest
  - python>3.9
  - ruff
  - shapely>=2.0
  - spyder
  - tomli
  - tomli-w
  - twine
  - xarray
